### ISSUE TITLE
Ecran de chargement

### ISSUE THREAD

**Issue by RobinTersou** [esgi18/DropAndFly#1]
**Contexte** :

Lors du lancement de l’application, un écran de chargement est affiché pendant le chargement des données.

**Déroulement** :

Lorsque l’application est lancée, on affiche la page de chargement (cf. #LAY01). Cette écran reste affiché tant que l’application n’est pas prête à être chargée. Une fois que tous les composants sont chargés, on affiche la page de connexion (cf. #LAY02).
En cas d’échec lors de ce chargement, un message d’erreur sera affiché sous forme de Toast (cf. #MSG00).

![lay01-loadingscreen](https://user-images.githubusercontent.com/22295399/51175365-6e002e00-18ba-11e9-9687-2eab4f70f1b3.png)

**Comment by adarracq** [comment]
Elle sert à rien l'appli le lancement de page de connexion est immédiat

**Comment by RobinTersou** [comment]
Il faut vérifier les connexions internet, connexions à la bdd, récupération des fichiers de conf etc.. 
Pour l'instant on a rien de tout ça mais cette page doit exister car, si par X raisons on ne peut pas accéder à un composant nécessaire à l'appli, c'est ici qu'on indiquera à l'utilisateur qu'il y a un problème plutôt qu'au milieu d'une réservation par exemple !

À implémenter quand même, même si inutile pour le moment
